/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.output.outside.root;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
